### ISSUE TITLE
DCMI Pin Configuration Incorrect

### ISSUE THREAD

**Issue by zainussami** [DL7AD/STM32F429-DCMI#1]
Hi Sven,

The pin configurations for DCMI_D3 and DCMI_D4 are incorrect, they should be PE1 (DCMI_D3) and PE4 (DCMI_D4)

Zain

**Comment by DL7AD** [comment]
Actually there can be multiple pins selected for the same function. But you are right. There's an error in the code.
By the way... I recognized that the camera connections are numbered incorrectly in the documentation.
It's a bit confusing: The camera has actually 10 data pins. But for RGB656 operation you only need 8 pins labeled from D2 to D9 at the camera. These are the pins which are available on the breakout board only.

| Camera Data pin | STM32 Data input | Possible Hardware Pins for DCMI |
| --- | --- | --- |
| D2 | D0 | PA9 PC6 PH9 |
| D3 | D1 | PA10 PC7 PH10 |
| D4 | D2 | PC8 PE0 PG10 PH11 |
| D5 | D3 | PC9 PE1 PG11 PH12 |
| D6 | D4 | PC11 PE4 PH14 |
| D7 | D5 | PB6 PD3 PI4 |
| D8 | D6 | PB8 PE5 PI6 |
| D9 | D7 | PB9 PE6 PI7 |

Sven

**Comment by zainussami** [comment]
Absolutely prefect on the code and docs, but the comments are confusing now.

This,
    palSetPadMode(GPIOC, 6, PAL_MODE_ALTERNATE(13)); // D5    -> PC6
    palSetPadMode(GPIOC, 7, PAL_MODE_ALTERNATE(13)); // D0    -> PC7
    palSetPadMode(GPIOC, 8, PAL_MODE_ALTERNATE(13)); // D1    -> PC8
    palSetPadMode(GPIOE, 1, PAL_MODE_ALTERNATE(13)); // D2    -> PE1
    palSetPadMode(GPIOE, 4, PAL_MODE_ALTERNATE(13)); // D3    -> PE4
    palSetPadMode(GPIOB, 6, PAL_MODE_ALTERNATE(13)); // D4    -> PB6
    palSetPadMode(GPIOE, 5, PAL_MODE_ALTERNATE(13)); // D6    -> PE5
    palSetPadMode(GPIOE, 6, PAL_MODE_ALTERNATE(13)); // D7    -> PE6
}

Should be

```
palSetPadMode(GPIOC, 6, PAL_MODE_ALTERNATE(13)); // D0   -> PC6
palSetPadMode(GPIOC, 7, PAL_MODE_ALTERNATE(13)); // D1    -> PC7
palSetPadMode(GPIOC, 8, PAL_MODE_ALTERNATE(13)); // D2    -> PC8
palSetPadMode(GPIOE, 1, PAL_MODE_ALTERNATE(13)); // D3    -> PE1
palSetPadMode(GPIOE, 4, PAL_MODE_ALTERNATE(13)); // D4    -> PE4
palSetPadMode(GPIOB, 6, PAL_MODE_ALTERNATE(13)); // D5    -> PB6
palSetPadMode(GPIOE, 5, PAL_MODE_ALTERNATE(13)); // D6    -> PE5
palSetPadMode(GPIOE, 6, PAL_MODE_ALTERNATE(13)); // D7    -> PE6
```

}
